package eu.hlavki.identity.services.push.model;

public enum EventType {

    APPLICATION_SETTINGS,
    CALENDAR_SETTINGS,
    CHAT_SETTINGS,
    CHROME,
    OS_SETTINGS,
    CONTACTS_SETTINGS,
    DELEGATED_ADMIN,
    DOCS_SETTINGS,
    DOMAIN_SETTINGS,
    EMAIL_SETTINGS,
    GROUP_SETTINGS,
    LICENSES_SETTINGS,
    MOBILE_SETTINGS,
    ORG_SETTINGS,
    SECURITY_SETTINGS,
    SITES_SETTINGS,
    SYSTEM_SETTINGS,
    USER_SETTINGS
}
